trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
  - job: SecondJob
    steps: 
    - bash: echo Build SecondJob
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'chuka001-Dockerhub'
      repository: 'chuka001/currency-exchange-devops'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags